In [1]:
import pandas as pd

#import data
temp_point_data = pd.read_csv(r"/home/engineering/Documents/PdM/data/temp_data/point_names.csv", low_memory=False)
temp_point_df = pd.DataFrame(temp_point_data)

In [2]:
filepath = "/home/engineering/Documents/PdM/data/temp_data/point_names.csv"

test_import = pd.read_csv(filepath, low_memory=False)
test_df = pd.DataFrame(test_import)
test_df.shape[0]

38

In [3]:
temp_point_df

   Point_Name                      Tag    TechID
0     Point_1       M630.FZ-1W26A.TEMP     1W26A
1     Point_2       M630.FZ-1W26B.TEMP     1W26B
2     Point_3       M630.FZ-1W26C.TEMP     1W26C
3     Point_4       M630.FZ-1W26D.TEMP     1W26D
4     Point_5       M630.FZ-1W17A.TEMP     1W17A
5     Point_6        M630.CR-1W26.TEMP      1W26
6     Point_7        M630.CR-1W27.TEMP      1W27
7     Point_8        M630.CR-1W28.TEMP      1W28
8     Point_9        M630.CR-1W17.TEMP      1W17
9    Point_10     M633.CR1S17.TEMP.RTD      1S17
10   Point_11     M633.CR1S20.TEMP.RTD      1S20
11   Point_12     M633.CR1P36.TEMP.RTD      1P36
12   Point_13     M633.CR1W09.TEMP.RTD      1W09
13   Point_14     M633.CR1W10.TEMP.RTD      1W10
14   Point_15         M633.RM4L04.TEMP      4L04
15   Point_16        M633.RM4L11A.TEMP     4L11A
16   Point_17        M633.RM4L26A.TEMP     4L26A
17   Point_18     M633.CR6P24.RTD.TEMP      6P24
18   Point_19        M633.CR-6P61.TEMP      6P61
19   Point_20  M636.WH.ENVIRO.ER1.TEMP       ER1
20   Point_21  M636.WH.ENVIRO.CR2.TEMP       ER2
21   Point_22  M636.WH.ENVIRO.CR3.TEMP       ER3
22   Point_23  M636.WH.ENVIRO.CR4.TEMP       ER4
23   Point_24  M636.WH.ENVIRO.CR5.TEMP       ER5
24   Point_25  M636.WH.ENVIRO.CR6.TEMP       ER6
25   Point_26  M636.QCL.CR-601001.TEMP  CR601001
26   Point_27  M636.INC.CR-601002.TEMP  CR601002
27   Point_28  M636.QCL.CR-601003.TEMP  CR601003
28   Point_29  M636.INC.CR-601005.TEMP  CR601005
29   Point_30       M660.QC.ER-12.TEMP      ER12
30   Point_31       M660.QC.ER-13.TEMP      ER13
31   Point_32    M660.WH.ER.S105A.TEMP     S105A
32   Point_33    M660.WH.ER.S105B.TEMP     S105B
33   Point_34    M660.WH.ER.S105C.TEMP     S105C
34   Point_35    M660.WH.CR.S101A.TEMP     S101A
35   Point_36    M660.WH.CR.S101B.TEMP     S101B
36   Point_37    M660.WH.CR.S101C.TEMP     S101C
37   Point_38    M660.WH.CR.S101D.TEMP     S101D

In [4]:
temp_data = pd.read_csv(r"/home/engineering/Documents/PdM/data/temp_data/temp_data_2026_01_19.csv", low_memory=False)
temp_df = pd.DataFrame(temp_data)
temp_df

,Date,Time,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_29,Point_30,Point_31,Point_32,Point_33,Point_34,Point_35,Point_36,Point_37,Point_38
0,1/1/2026,00:00:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
1,1/1/2026,00:01:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
2,1/1/2026,00:02:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
3,1/1/2026,00:03:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
4,1/1/2026,00:04:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26411,1/19/2026,08:11:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-40.04
26412,1/19/2026,08:12:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-40.04
26413,1/19/2026,08:13:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-40.04
26414,1/19/2026,08:14:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-41.04
26415,1/19/2026,08:15:00,-41.37,-41.39,-40.45,-40.42,-20.84,4.51,5.01,5.63,...,5.09,5.09,5.58,4.77,-20.64,-40.14,5.00,-39.08,5.19,-41.64

In [5]:
test_df = temp_df.copy()
test_df

,Date,Time,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_29,Point_30,Point_31,Point_32,Point_33,Point_34,Point_35,Point_36,Point_37,Point_38
0,1/1/2026,00:00:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
1,1/1/2026,00:01:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
2,1/1/2026,00:02:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
3,1/1/2026,00:03:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
4,1/1/2026,00:04:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26411,1/19/2026,08:11:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-40.04
26412,1/19/2026,08:12:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-40.04
26413,1/19/2026,08:13:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-40.04
26414,1/19/2026,08:14:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-41.04
26415,1/19/2026,08:15:00,-41.37,-41.39,-40.45,-40.42,-20.84,4.51,5.01,5.63,...,5.09,5.09,5.58,4.77,-20.64,-40.14,5.00,-39.08,5.19,-41.64

In [6]:
point_num = []
point_name = []
for i in temp_point_df.loc[:,"Point_Name"]:
    point_num.append(i)
for j in temp_point_df.loc[:,"TechID"]:
    point_name.append(j)

rename_dict = {}
for k in range(0,38):
    rename_dict[point_num[k]] = point_name[k]
rename_dict

{'Point_1': '1W26A',
 'Point_2': '1W26B',
 'Point_3': '1W26C',
 'Point_4': '1W26D',
 'Point_5': '1W17A',
 'Point_6': '1W26',
 'Point_7': '1W27',
 'Point_8': '1W28',
 'Point_9': '1W17',
 'Point_10': '1S17',
 'Point_11': '1S20',
 'Point_12': '1P36',
 'Point_13': '1W09',
 'Point_14': '1W10',
 'Point_15': '4L04',
 'Point_16': '4L11A',
 'Point_17': '4L26A',
 'Point_18': '6P24',
 'Point_19': '6P61',
 'Point_20': 'ER1',
 'Point_21': 'ER2',
 'Point_22': 'ER3',
 'Point_23': 'ER4',
 'Point_24': 'ER5',
 'Point_25': 'ER6',
 'Point_26': 'CR601001',
 'Point_27': 'CR601002',
 'Point_28': 'CR601003',
 'Point_29': 'CR601005',
 'Point_30': 'ER12',
 'Point_31': 'ER13',
 'Point_32': 'S105A',
 'Point_33': 'S105B',
 'Point_34': 'S105C',
 'Point_35': 'S101A',
 'Point_36': 'S101B',
 'Point_37': 'S101C',
 'Point_38': 'S101D'}

In [7]:
test_df.rename(columns=rename_dict)

,Date,Time,1W26A,1W26B,1W26C,1W26D,1W17A,1W26,1W27,1W28,...,CR601005,ER12,ER13,S105A,S105B,S105C,S101A,S101B,S101C,S101D
0,1/1/2026,00:00:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
1,1/1/2026,00:01:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
2,1/1/2026,00:02:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
3,1/1/2026,00:03:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
4,1/1/2026,00:04:00,-41.12,-41.41,-40.68,-40.44,-20.63,4.53,5.00,5.54,...,5.16,5.26,5.24,5.49,-20.29,-39.07,5.00,-39.34,4.84,-41.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26411,1/19/2026,08:11:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-40.04
26412,1/19/2026,08:12:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-40.04
26413,1/19/2026,08:13:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-40.04
26414,1/19/2026,08:14:00,-41.37,-41.39,-40.73,-40.41,-20.84,4.51,5.04,5.62,...,5.09,5.06,4.86,4.76,-21.40,-39.07,4.99,-39.79,5.18,-41.04
26415,1/19/2026,08:15:00,-41.37,-41.39,-40.45,-40.42,-20.84,4.51,5.01,5.63,...,5.09,5.09,5.58,4.77,-20.64,-40.14,5.00,-39.08,5.19,-41.64

In [8]:
import csv
import pandas as pd

path = '/home/engineering/Documents/PdM/data/test.txt'
path1 = '/home/engineering/Documents/PdM/data/amp_press_data/point_names.csv'

try:
    with open(path, 'r', newline='') as f:
        sample = f.read(2048)
        dialect = csv.Sniffer().sniff(sample)
    if dialect.delimiter == ',':
        data = pd.read_csv(path, low_memory=False)
        df_data = pd.DataFrame(data)
    else:
        raise csv.Error
    
except csv.Error:
    print('try not successful')

try not successful

In [9]:
import utilities

In [10]:
path1 = '/home/engineering/Documents/PdM/data/amp_press_data/raw/refrigerant_monitoring_2026_01_19.csv'
path2 = '/home/engineering/Documents/PdM/data/amp_press_data/raw/refrigerant_monitoring_2026_01_28.csv'

In [11]:
df1 = utilities.import_csvfile(path1)
df2 = utilities.import_csvfile(path2)

In [12]:
df1.tail(10)

,<>Date,Time,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_10,Point_11,Point_12,Point_13,Point_14,Point_15,Point_16,Point_17,Point_18,Point_19
26512,1/19/2026,09:52:00,No Data,No Data,No Data,No Data,-40.36,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
26513,1/19/2026,09:53:00,No Data,No Data,No Data,No Data,-40.28,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
26514,1/19/2026,09:54:00,No Data,No Data,No Data,No Data,-40.05,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
26515,1/19/2026,09:55:00,No Data,No Data,No Data,No Data,-40.05,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
26516,1/19/2026,09:56:00,No Data,No Data,No Data,No Data,-40.05,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
26517,1/19/2026,09:57:00,No Data,No Data,No Data,No Data,-40.17,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
26518,1/19/2026,09:58:00,No Data,No Data,No Data,No Data,-40.28,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
26519,1/19/2026,09:59:00,No Data,No Data,No Data,No Data,-40.36,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
26520,1/19/2026,10:00:00,No Data,No Data,No Data,No Data,-40.43,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data
26521,1/19/2026,10:01:00,No Data,No Data,No Data,No Data,-40.58,No Data,No Data,No Data,...,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data,No Data

In [13]:
df2.head(10)

,<>Date,Time,Point_1,Point_2,Point_3,Point_4,Point_5,Point_6,Point_7,Point_8,...,Point_10,Point_11,Point_12,Point_13,Point_14,Point_15,Point_16,Point_17,Point_18,Point_19
0,1/19/2026,00:00:00,0.83,155,27.68,265,-40.58,0.02,167,12.83,...,5.16,15.07,237,0.04,5.31,175,0.04,89.53,0.17,114.09
1,1/19/2026,00:01:00,0.83,155,27.68,265,-40.58,0.02,167,12.91,...,5.16,15.07,232,0.04,5.31,175,0.04,87,0.17,111.59
2,1/19/2026,00:02:00,0.83,155,27.68,265,-40.58,0.02,167,11.89,...,5.16,15.07,232,0.04,5.31,175,0.04,87,0.17,109.09
3,1/19/2026,00:03:00,0.83,155,27.68,265,-40.58,0.02,167,12.98,...,5.16,15.07,235,0.04,5.31,175,0.04,87,0.17,106.47
4,1/19/2026,00:04:00,0.83,155,27.68,265,-40.58,0.02,167,11.97,...,5.16,15.07,235,0.04,5.31,175,0.04,87,0.17,103.94
5,1/19/2026,00:05:00,0.83,155,27.68,265,-40.58,0.02,167,11.97,...,5.16,15.07,229,0.04,5.31,175,0.04,87,0.17,103.94
6,1/19/2026,00:06:00,0.83,155,27.68,265,-40.58,0.02,167,12.99,...,5.16,15.07,232,0.04,5.31,175,0.04,87,0.17,101.44
7,1/19/2026,00:07:00,0.83,155,27.68,265,-40.58,0.02,167,12.99,...,5.16,15.07,232,0.04,5.31,175,0.04,87,0.17,98.94
8,1/19/2026,00:08:00,0.83,155,27.68,265,-40.58,0.02,167,14.01,...,5.16,15.07,237,0.04,5.31,175,0.04,87,0.17,98.94
9,1/19/2026,00:09:00,0.83,155,27.68,265,-40.58,0.02,167,15.09,...,5.16,15.07,232,0.04,5.31,175,0.04,87,0.17,98.94

In [ ]:
df31 = {
    "item": [101, 102, 103, 104, 105],
    "Point_1": [0.1, 0.15, 0.12, "No Data", "No Data"],
    "Point_2": [0.2, 0.3, 0.25, "No Data", "No Data"],
    "Point_3": [0.53, 0.60, 0.57, "No Data", "No Data"],
    "Point_4": [0.07, 0.09, 0.12, "No Data", "No Data"],
    "Point_5": [0.5, 0.51, 0.5, "No Data", "No Data"]
}

df41 = {
    "item": [104, 105, 106, 107, 108],
    "data": [0.14, 0.1, 0.13, 0.15, 0.17]
}
item	Point_1_x	Point_2_x	Point_3_x	Point_4_x	Point_5_x	Point_1_y	Point_2_y	Point_3_y	Point_4_y	Point_5_y
0	101	0.10	0.20	0.53	0.07	0.50	NaN	NaN	NaN	NaN	NaN
1	102	0.15	0.30	0.60	0.09	0.51	NaN	NaN	NaN	NaN	NaN
2	103	0.12	0.25	0.57	0.12	0.50	NaN	NaN	NaN	NaN	NaN
3	104	NaN	NaN	NaN	NaN	NaN	0.14	0.20	0.53	0.07	0.50
4	105	NaN	NaN	NaN	NaN	NaN	0.10	0.30	0.60	0.09	0.51
5	106	NaN	NaN	NaN	NaN	NaN	0.13	0.25	0.57	0.12	0.50
6	107	NaN	NaN	NaN	NaN	NaN	0.15	0.28	0.59	0.18	0.55
7	108	NaN	NaN	NaN	NaN	NaN	0.17	0.30	0.60	0.20	0.60

In [ ]:
df3 = df3.replace("No Data", np.nan)

/tmp/ipykernel_4672/928865625.py:27: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df3 = df3.replace("No Data", np.nan)

In [42]:
df3

   item  Point_1  Point_2  Point_3  Point_4  Point_5
0   101     0.10     0.20     0.53     0.07     0.50
1   102     0.15     0.30     0.60     0.09     0.51
2   103     0.12     0.25     0.57     0.12     0.50
3   104      NaN      NaN      NaN      NaN      NaN
4   105      NaN      NaN      NaN      NaN      NaN

In [43]:
df3.join(df4)

ValueError: columns overlap but no suffix specified: Index(['item', 'Point_1', 'Point_2', 'Point_3', 'Point_4', 'Point_5'], dtype='object')

In [ ]:
merged =pd.merge(df3, df4, on="item", how = "outer")

In [37]:
merged

,item,Point_1_x,Point_2_x,Point_3_x,Point_4_x,Point_5_x,Point_1_y,Point_2_y,Point_3_y,Point_4_y,Point_5_y
0,101,0.10,0.20,0.53,0.07,0.50,NaN,NaN,NaN,NaN,NaN
1,102,0.15,0.30,0.60,0.09,0.51,NaN,NaN,NaN,NaN,NaN
2,103,0.12,0.25,0.57,0.12,0.50,NaN,NaN,NaN,NaN,NaN
3,104,NaN,NaN,NaN,NaN,NaN,0.14,0.20,0.53,0.07,0.50
4,105,NaN,NaN,NaN,NaN,NaN,0.10,0.30,0.60,0.09,0.51
5,106,NaN,NaN,NaN,NaN,NaN,0.13,0.25,0.57,0.12,0.50
6,107,NaN,NaN,NaN,NaN,NaN,0.15,0.28,0.59,0.18,0.55
7,108,NaN,NaN,NaN,NaN,NaN,0.17,0.30,0.60,0.20,0.60